OBJECTIVE_CHOICES = (
        'APP_INSTALLS',
        'BRAND_AWARENESS',
        'EVENT_RESPONSES',
        'LEAD_GENERATION',
        'LINK_CLICKS',
        'LOCAL_AWARENESS',
        'MESSAGES',
        'OFFER_CLAIMS',
        'PAGE_LIKES',
        'POST_ENGAGEMENT',
        'PRODUCT_CATALOG_SALES',
        'REACH',
        'STORE_VISITS',
        'VIDEO_VIEWS',
        'CONVERSIONS',
    )
BILLING_EVENT_CHOICES = (
        'APP_INSTALLS',
        'CLICKS',
        'IMPRESSIONS',
        'LINK_CLICKS',
        'LISTING_INTERACTION',
        'NONE',
        'OFFER_CLAIMS',
        'PAGE_LIKES',
        'POST_ENGAGEMENT',
        'THRUPLAY',
    )
OPTIMIZATION_GOAL_CHOICES = (
        'AD_RECALL_LIFT',
        'APP_INSTALLS',
        'APP_INSTALLS_AND_OFFSITE_CONVERSIONS',
        'CONVERSATIONS',
        'DERIVED_EVENTS',
        'ENGAGED_USERS',
        'EVENT_RESPONSES',
        'IMPRESSIONS',
        'LANDING_PAGE_VIEWS',
        'PAGE_LIKES',
        'NONE',
        'OFFSITE_CONVERSIONS',
        'PAGE_LIKES',
        'POST_ENGAGEMENT',
        'QUALITY_CALL',
        'QUALITY_LEAD',
        'REACH',
        'THRUPLAY',
        'VALUE',
        'VISIT_INSTAGRAM_PROFILE',
)
CURRENCY_CHOICES = (
        'AED',
        'SAR',
        'USD',
        'EUR',
        'TRY',
    )

STATUS_CHOICES = (
        'ACTIVE',
        'ARCHIVED',
        'DELETED',
        'PAUSED',
    )